MVC for Skill database.
flozender/BuildIT pull request #103
Opened 2021-02-01 04:51 UTC by talha8045

2021-02-02 11:29 UTC, flozender requested changes
Please make the changes

2021-02-02 18:07 UTC, talha8045 commented on Client/index.js
> -    ];
Done. I've added headers loop back.

2021-02-03 07:05 UTC, talha8045 commented on Client/views/skilladd.ejs
> +<!DOCTYPE html>
Done. lastly i have to replace 'weekId: String' with 'weekId: Date()'.

2021-02-03 10:51 UTC, talha8045 commented
Done. i committed all the chages you suggested.

2021-02-04 11:09 UTC, flozender commented
Let's sort this to the latest week on top followed by the other in the order. And if a CSV is uploaded for a week that already has a record, update it, it's creating multiple copies right now. 
![image](https://user-images.githubusercontent.com/40818234/106884619-8d6b8d00-6707-11eb-8f95-5d2ac9bf9bde.png)

2021-02-04 11:16 UTC, flozender commented
On selecting a previous week, let's make the date show up here 
![image](https://user-images.githubusercontent.com/40818234/106885341-7bd6b500-6708-11eb-85f8-dc4444c68800.png)

2021-02-04 11:19 UTC, flozender commented on Client/views/skilladd.ejs
> +<!DOCTYPE html>
No, `weekId: String` is right, since it's still an ID that happens to be in the format of a date.

2021-02-04 11:54 UTC, flozender commented
Since you added a new ejs file, remove `uploadcsv.ejs` they both do the same thing.

2021-02-04 12:56 UTC, flozender requested changes

2021-02-04 12:56 UTC, flozender commented on Client/index.js
> +    serverurl: serverRoute + "/updateLeaderboard",
I think we don't need this anymore right? Since you have your `/skillExcel` endpoint for leaderboard updation?

2021-02-04 14:16 UTC, talha8045 commented on Client/index.js
> +    serverurl: serverRoute + "/updateLeaderboard",
I shall remove it.

2021-02-09 03:48 UTC, flozender requested changes
Final review before we merge

2021-02-09 03:48 UTC, flozender commented on Client/index.js
>  app.get("/skillup365", async (req, res) => {
Why do we have an `app.get("/skillup365",)` and an `app.get("/skill",)`? Remove the one you're not using.

2021-02-09 03:48 UTC, flozender commented on Client/views/leaderboard.ejs
> +        <select class="dropdown" name="weekId" onchange="javascript:$('#submit').click();">
```suggestion
        <select class="dropdown custom-select" name="weekId" onchange="javascript:$('#submit').click();">
```

2021-02-09 08:01 UTC, talha8045 commented on Client/index.js
>  app.get("/skillup365", async (req, res) => {
It is done.

2021-02-09 08:01 UTC, talha8045 commented on Client/views/leaderboard.ejs
> +        <select class="dropdown" name="weekId" onchange="javascript:$('#submit').click();">
Okay

2021-02-09 10:24 UTC, flozender requested changes

2021-02-09 10:24 UTC, flozender commented on Client/views/leaderboard.ejs
> +          <a href="../images/SkillUp.pdf">
```suggestion
          <a href="../images/SkillUP.pdf">
```

2021-02-09 10:34 UTC, flozender commented on Client/views/uploadcsv.ejs
> +				background:#fff url(https://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/calendar_2.png)  97% 50% no-repeat;
Save this image locally and link it here, the URL may change in the future, which will break the UI.

2021-02-09 11:00 UTC, talha8045 commented on Client/views/uploadcsv.ejs
> +				background:#fff url(https://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/calendar_2.png)  97% 50% no-repeat;
The image is now saved locally.

2021-02-09 11:01 UTC, merged

2021-02-09 11:02 UTC, flozender commented
Thanks for the great PR!